name: Build Parser

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build lexer
        run: |
          chmod +x ./compile.sh
          ./compile.sh
